### ISSUE TITLE
Release Candidate 1.1.0 RC1

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/policy-hub#171]
### Summary
Build the new release candidate of "policy hub" (see components below) and deploy to association integration env.
Execute the release process in the eclipse-tractusx organisation.
Branch: Release Branch

### Tasks:

- [x]  changelog created
- [x]  release (version bump, changelog, update readme, release new helm chart, merge release branch)
- [x]  provide successive release branch (tractusx und ng-forks) for release closure
- [x]  change base of open PRs
- [x]  user info/association info
- [x]  deploy to integration environment
- [x]  inform team members of the deployment status
