### ISSUE TITLE
New Policy "contractReference" type

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/policy-hub#176]
### Description
A new policy named "contractReference" with the right operand "{bilateralContractName}" needs to be implemented. This policy can be used for any `useCase` type and should be active as of today. No regex or transactional attributes are required for this policy.

### Acceptance Criteria
1. The new "contractReference" policy should be added to the system.
2. The right operand for the policy should be set to "{bilateralContractName}".
3. The policy should be applicable for any `useCase` type.
4. The policy should be active as of today's date.
5. No regex or transactional attributes should be required for this policy.

### Tasks
1. Add the new "contractReference" policy to the system.
2. Set the right operand for the policy to "{bilateralContractName}".
3. Ensure the policy is applicable for any `useCase` type.
4. Set the policy to be active as of today's date.
5. Verify that no regex or transactional attributes are required for this policy.

### Definition of Done
- [ ] New "contractReference" policy added to the system
- [ ] Right operand set to "{bilateralContractName}"
- [ ] Policy applicable for any `useCase` type
- [ ] Policy can get used for "Usage" types only
- [ ] Policy active as of today's date
- [ ] No regex or transactional attributes required
- [ ] All acceptance criteria met
- [ ] Implementation tested and verified

**Comment by evegufy** [comment]
@sachinargade123 @ciprianherciu it's ready for testing
