### ISSUE TITLE
Documentation Ticket: Adding Attributes and Policies

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/policy-hub#178]
### Description
Code documentation is needed on how to add additional attributes as well as how to add new policies to the policy hub

### Acceptance Criteria
1. Provide documentation on the process of adding new attributes to the system.
2. Provide documentation on the process of adding new policies to the system.
3. The documentation should be clear, concise, and easy to follow.
4. The documentation should be made available to the relevant stakeholders.

### Tasks
1. Gather information on the current process for adding new attributes and policies.
2. Document the steps involved in adding new attributes, including any required configurations or settings.
3. Document the steps involved in adding new policies, including any required configurations or settings.
4. Review the documentation with the relevant stakeholders and incorporate any feedback.

### Where
https://github.com/eclipse-tractusx/policy-hub under /docs

### Definition of Done
- [ ] Documentation on adding new attributes completed
- [ ] Documentation on adding new policies completed
- [ ] Documentation reviewed and approved by stakeholders
- [ ] Documentation published and made accessible
